# H2 Database Configuration (in-memory for development)
spring:
  application:
    name: ai-workflow-backend
  datasource:

    # H2 Database Configuration (in-memory for development)
    url: jdbc:h2:mem:aiworkflowdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    # JPA/Hibernate Configuration
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Automatically create/update schema based on entities
      ddl-auto: update
    # Show SQL queries in console (useful for debugging)
    show-sql: true
  h2:
    # Enable H2 console for easy database viewing (access at http://localhost:8080/h2-console)
    console:
      enabled: true
      path: /h2-console

# Server Port (optional, default is 8080)
# server:
#   port: 8080
